### ISSUE TITLE
this uses typetools

### ISSUE THREAD

**Issue by Nuclearfarts** [architectury/architectury-api#1]
please do not use typetools it's awful and WILL break on every new java version

**Comment by shedaniel** [comment]
send help what can i use

**Comment by Nuclearfarts** [comment]
just have people pass the type

**Comment by shedaniel** [comment]
that sounds evil

**Comment by Nuclearfarts** [comment]
less evil than typetools

**Comment by shedaniel** [comment]
This is removed in 2.0.
