### ISSUE TITLE
org.spongepowered errors; Bloated logs

### ISSUE THREAD

**Issue by BigDiccMarty** [architectury/architectury-api#176]
Architectury is causing bloated logs for server and clients reaching several hundred megabytes in a few seconds of in world activity.

Ex: `Mixin apply for mod architectury failed architectury.mixins.json:MixinChunkSerializer -> net.minecraft.class_2852: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> architectury.mixins.json:MixinChunkSerializer -> Apply Methods -> (Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2843;ZLnet/minecraft/class_2499;I[Lnet/minecraft/class_2826;ZLnet/minecraft/class_2802;Lnet/minecraft/class_3568;Lnet/minecraft/class_2378;JLnet/minecraft/class_2806$class_2808;Lnet/minecraft/class_6752;Lnet/minecraft/class_2791;)V:handler$zda000$load -> Transform LVT -> var=generationUpgradeData -> desc=Lnet/minecraft/class_6752;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> architectury.mixins.json:MixinChunkSerializer -> Apply Methods -> (Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2843;ZLnet/minecraft/class_2499;I[Lnet/minecraft/class_2826;ZLnet/minecraft/class_2802;Lnet/minecraft/class_3568;Lnet/minecraft/class_2378;JLnet/minecraft/class_2806$class_2808;Lnet/minecraft/class_6752;Lnet/minecraft/class_2791;)V:handler$zda000$load -> Transform LVT -> var=generationUpgradeData -> desc=Lnet/minecraft/class_6752;]
	at
org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at...`
	_Errors cut off, repeats, causing gigabytes of logs in a few minutes_

![modlist](https://user-images.githubusercontent.com/97356649/148653983-9624f395-1be1-420f-bc9c-6c864c27dab8.png)

List of mods being used.

**Comment by Juuxel** [comment]
Bloated logs are the least of the problems here - the error means the chunk serialiser can't be loaded and the world can't probably be saved at all. Your Architectury API version is very outdated, so try updating to 3.4.9/the latest to see if it fixes your problem.

(Also note that you seem to be running Fabric but also having Forge mods, which won't load under Fabric)

**Comment by BigDiccMarty** [comment]
I see the issue. Sorry.

The "Beta" version of Architectury on the CurseForge website is 3.0.37 while the release version is 3.4.9
![image](https://user-images.githubusercontent.com/97356649/148661227-a52811ce-ca59-4be9-822a-c4a143e15a64.png)

This is an issue.

The other Forge Mods don't affect anything and are nothing but bloat, so they are luckily not an issue. 

Thank you for helping.

**Comment by shedaniel** [comment]
Unfortunately the beta version being older is not solvable by us, it is a problem on CurseForge for how it decides to display those. You should check the date before downloading
